[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/unified_home.html"
  to = "/unified_home.html"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
